.TH hearth 8 2012-mar "linux" "heatherly custom tools manual"

.SH NAME
hearth_estia \- clean, custom, and secure terminal login replacement

.SH IMAGERY
hearth (לשתנט) is a symbol of one's home, a place of welcoming guests

.SH SUMMARY
hearth is a clean, custom, maintainable, reliable, and secure login
replacement utilty that will take the place of both login and su while 
increasing monitoring, notification, and logging.

.SH SYNOPSIS
.nf
.B hearth [URGENTS] [OPTIONS] <dev_file>

.SH COMMAND LINE OPTIONS
hearth can alter its display a number of ways to aid login and debugging.

.B hestia, 
these options allow hestia (getty) to transfer critical information easily
to hearth (login).

.B --hostname <text>
.RS 8
transfers the hostname string
.RE

.B --cluster <n>
.RS 8
transfers the cluster number
.RE

.B /dev/tty<n>
.RS 8
specifies the device for the login
.RE

.B informational, 
these options provide simple additional information on the program.

.B --version
.RS 8
displays version number and comment then exits
.RE

.B hinting, 
these options provide additional help in locating and interpreting login
information for new or inexperienced users.

.B --color (default), --nocolor
.RS 8
display in color or all white, on a transparent background
.RE

.B --hints, --nohints (default)
.RS 8
colorize key elements which can aid a end-user to login
.RE

.B --counters, --nocounters (default)
.RS 8
show small information windows with debugging information
.RE

.B --rotpnt (default), --norotpnt
.RS 8
display rotation and suffix pointers in midline
.RE

.B visual display, 
these options are primarily for debugging purposes as some of the elements
contain critical login information.

.B --butterfly (default), --nobutterfly
.RS 8
display the center butterfly ascii art
.RE

.B --bfly <n>
.RS 8
allows the caller to specify a specific image
.RE

.B --status (default), --nostatus
.RS 8
display the topmost line that provides current status
.RE

.B --knock (default), --noknock
.RS 8
display the dots and dashes for the knock
.RE

.B --left (default), --noleft
.RS 8
display the leftmost numbers for prefix and infix
.RE

.B --right (default), --noright
.RS 8
display the rightmost numbers for suffix
.RE

.B --middle (default), --nomiddle
.RS 8
display the middle line of letters/numbers
.RE

.B --binary (default), --nobinary
.RS 8
display the bottom left binary codes
.RE

.B --prompt (default), --noprompt
.RS 8
display the traditional login prompting
.RE

.B --tty (default), --notty
.RS 8
display information about terminal
.RE

.B --external (default), --internal
.RS 8
display information about external vs internal sessions
.RE

.B --judgement (default), --nojudgement
.RS 8
display narrative feedback about login
.RE

.B timer and timeout, 
these options provide additional information and control over login session
timeout and status

.B --timer (default), --notimer
.RS 8
display the timer at the bottom
.RE

.B --timeout, --notimeout (default)
.RS 8
display the timeout period in tenths of a second
.RE

.B --infinite, --finite (default)
.RS 8
allow the user session to timeout
.RE

.B --timeout <tenths>
.RS 8
timeout period in tenths of seconds
.RE

.B interactive, 
these options allow the system to be run from the command line to aid in
debugging and testing.

.B --fake (default), --nofake
.RS 8
turn the initial login screen on or off
.RE

.B <username>
.RS 8
provide a command line username string
.RE

.SH FILES
hearth will not alter or update any unix standard input or output files
including...
   -- /etc/passwd             -- for valid users and characteristics
   -- /etc/shadow             -- for encrypted passwords
   -- /var/log/wtmp           -- historical logging
   -- /var/run/utmp           -- current logging
   -- /var/log/btmp           -- failed log on logging
   -- /var/log/lastlog        -- last successful log on logging
   -- /var/log/sulog          -- use of su logging

hestia and hearth will add a few files in order to support configuration
and consistency checking...
   -- /var/log/hestia.logging -- supplementary logging
   -- /etc/hestia.conf        -- hestia configuration

.SH SEE ALSO
this documentation is layered to provide easier navigation.
   hearth (7), decision rationale, objectives, and overview
   hearth (8), initiation, options, and structure

.SH AUTHOR
jelloshrke ata gmail dotta com

.SH COLOPHON
this page is part of a documentation package meant to make our use of the
heatherly tools easier and faster

