.TH hearth 7 2012-mar "linux" "heatherly custom tools manual"

.SH NAME
hearth \- decision rationale, objectives, and overview

.SH SUMMARY
hearth is a flexible, adaptive, maintainable, reliable, and secure login
replacement utilty that will take the place of login, su, and x11 login while
increasing monitoring, notification, and logging.

.SH SCOPE, REASONING and DECISION

.B definition (D).   
login services are used by interactive users to request, validate, and
establish a new session with the system -- traditionally requiring only a
user name and password from the user.

.B WTF (W).   
no one in their right mind rebuilds a well-tested, fundamental system.  well,
i want to learn this critical area.  i actually feel login has squashed
creativity by being so steady and good.

.B value (V).   
most linux systems are only guarded by physical/electronic access and login
serices.  the importance of a strong, flexible, and adaptive login system
can not be overstated.

.B complication (C).   
traditional login services have been a mainstay in security, but have not
been updated with new thinking and theories, mainly due to user complaints
about any additional work.

.B answer (A).   
i will build a fully custom, very specific login services system to test any
and all innovative methods for denying crackers, hackers, script-kiddies,
robots, and, well, anyone but me.

.B target user (T).  
very technical, well-versed, power user.

.B drawbacks...
   -- replacing a tried, tested, and working system
   -- must become knowledgeable on digital security systems
   -- may introduce explotable bugs along the way
   -- one more thing i need to maintain
   -- nobody else will ever want such a thing

.B benefits...
   -- develop a bigger knowledge base in this critical area
   -- pressure me to create more stable programs (reduce maintenance)
   -- make my systems much more defensable that the next guy
   -- get rid of dependence on other people's login systems
   -- experiment like crazy and find new great methods

.B known experiments...
   -- two-factor authentication
   -- sms call/response
   -- bluetooth from phone
   -- embedded information in screen presention
   -- hall detector from ring or other wearable
   -- work schedule restrictions
   -- source point restrictions

.SH SEE ALSO
this documentation is layered to provide easier navigation.
   hearth (7), decision rationale, objectives, and overview
   hearth (8), clean, custom, and secure terminal login replacement

.SH AUTHOR
jelloshrike ata gmail dotta com

.SH COLOPHON
this page is part of a documentation package meant to make use of the
heatherly tools easier and faster.
